# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', :deterministic_uuids => false

target 'TestNAWithRN' do
  # Comment the next line if you don't want to use dynamic frameworks
  
#use_frameworks!
use_frameworks! :linkage => :static



  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Pods for TestNAWithRN

  target 'TestNAWithRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestNAWithRNUITests' do
    # Pods for testing
  end


end
